const en = {
    i18n_titulo: 'Aerosol Risks Calculator',
    i18n_descripcion: 'Select the place/room on which you want to calculate the risk transmission by aerosols of <b> COVID-19 </b>',
    i18n_subdivision: 'Place / Resort',
    i18n_class: 'Class',
    i18n_coro: 'Master-Choir',
    i18n_estadio: 'Stadium',
    i18n_metro: 'Subway',
    i18n_super: 'Supermarket',
    i18n_tasa_ventilacion_persona: 'Ventilation rate per person',
    i18n_l_s_persona: 'L/s/person',
    i18n_parametros_ambientales: 'Environmental Parameters',
    i18n_largo: 'Lenght',
    i18n_ancho: 'Width',
    i18n_alto: 'Height',
    i18n_duracion_evento: 'Duration of event',
    i18n_n_rep_evento: 'Number rep. event',
    i18n_cambios_aire: 'Ventilation w/ outside air',
    i18n_mostrar: 'Show',
    i18n_ocultar: 'Hide',
    i18n_parametros_avanzados: 'Advanced Parameters',
    i18n_presion: 'Presure',
    i18n_temperatura: 'Temperature',
    i18n_humedad: 'Humidity',
    i18n_co2_aire_libre: 'Background CO2 Outdoors',
    i18n_tasa_descomposicon: 'Decay rate of the virus',
    i18n_deposicon_superficies: 'Deposition to surfaces',
    i18n_medidas_control_adicionales: 'Additional control measures',
    i18n_densidad_area_persona: 'Density <br /> (area/person)',
    i18n_ft_persona: 'sq ft/person',
    i18n_persona_m2: 'person/m2',
    i18n_m3_persona: 'm3/person',
    i18n_parametros_personas_actividad: 'Parameters related to people and activity in the room',
    i18n_n_personas: 'Number people',
    i18n_poblacion_inmune: 'Inmune population',
    i18n_frec_respiratoria: 'Breathing rate',
    i18n_exhalacion_cuantica: 'Quanta exhalation rate',
    i18n_ef_mascarilla_exhalacion: 'Exhalation mask efficiency',
    i18n_personas_con_mascarillas: 'Fraction of people w/ masks',
    i18n_ef_mascarilla_inhalacion: 'Inhalation mask efficiency',
    i18n_personas_infecciosas: 'Infective people',
    i18n_tasa_co2_por_persona: 'CO2 emission rate (1 person)',
    i18n_parametros_covid19: 'COVID-19 Parameters',
    i18n_probabilidad_ser_infeccioso: 'Probability of being infective',
    i18n_tasa_hospitalizacion: 'Hospitalization rate',
    i18n_indice_mortalidad: 'Death rate',
    i18n_resultado_condicional_evento: 'Conditional result for one event',
    i18n_una_persona_un_evento: 'ONE PERSON / ONE EVENT',
    i18n_prob_infeccion: 'Probability of infection',
    i18n_prob_hospitalizacion: 'Probability of hospitalization',
    i18n_prob_muerte: 'Probability of death',
    i18n_relacion_riesgo_muerte_automovil: 'Relationship with the risk of death due to car travel',
    i18n_todos_asistentes_evento: 'ALL ASSISTANTS / ONE EVENT',
    i18n_casos_covid_surgidos: 'COVID cases arising',
    i18n_hospitalizaciones_surgidas: 'Hospitalizations arising',
    i18n_muertes_surgidas: 'Deaths arising',
    i18n_resultado_absoluto_evento: 'Result absolute/event',
    i18n_co2_inhalar: 'CO2 to inhale 1 hour to infect 1% (ppm)',
    i18n_resultado_absoluto_multiples_veces: 'Result absolute/multiple times',
    i18n_notas_particulares: 'Particular notes for this case',
    i18n_mas_info: 'More Information'
}