const es = {
    i18n_titulo: 'Calc. Riesgos Aerosoles',
    i18n_descripcion: 'Selecciona el lugar/estancia sobre la que quiere calcular la transmisión de riesgos por aerosoles de la <b>COVID-19</b>',
    i18n_subdivision: 'Lugar / Estancia',
    i18n_class: 'Clase',
    i18n_coro: 'Coro',
    i18n_estadio: 'Estadio',
    i18n_metro: 'Metro',
    i18n_super: 'Super',
    i18n_tasa_ventilacion_persona: 'Tasa de ventilación por persona',
    i18n_l_s_persona: 'L/s/persona',
    i18n_parametros_ambientales: 'Parametros ambientales',
    i18n_largo: 'Largo',
    i18n_ancho: 'Ancho',
    i18n_alto: 'Alto',
    i18n_duracion_evento: 'Duracion evento',
    i18n_n_rep_evento: 'Nº rep. evento',
    i18n_cambios_aire: 'Cambios de aire',
    i18n_mostrar: 'Mostrar',
    i18n_ocultar: 'Ocultar',
    i18n_parametros_avanzados: 'Parametros avanzados',
    i18n_presion: 'Presión',
    i18n_temperatura: 'Temperatura',
    i18n_humedad: 'Humedad',
    i18n_co2_aire_libre: 'CO2 al aire libre',
    i18n_tasa_descomposicon: 'Tasa descomposicón',
    i18n_deposicon_superficies: 'Deposicón superficies',
    i18n_medidas_control_adicionales: 'Medidas control adicionales',
    i18n_densidad_area_persona: 'Densidad <br /> (área/persona)',
    i18n_ft_persona: 'sq ft/persona',
    i18n_persona_m2: 'persona/m2',
    i18n_m3_persona: 'm3/persona',
    i18n_parametros_personas_actividad: 'Parametros Personas & Actividad',
    i18n_n_personas: 'Nº Personas',
    i18n_poblacion_inmune: 'Población inmune',
    i18n_frec_respiratoria: 'Frec. respiratoria',
    i18n_exhalacion_cuantica: 'Exhalación cuántica',
    i18n_ef_mascarilla_exhalacion: 'Ef. mascarilla exhalación',
    i18n_personas_con_mascarillas: 'Personas con mascarillas',
    i18n_ef_mascarilla_inhalacion: 'Ef. mascarilla inhalación',
    i18n_personas_infecciosas: 'Pers. infecciosas',
    i18n_tasa_co2_por_persona: 'Tasa CO2 por persona',
    i18n_parametros_covid19: 'Parametros COVID-19',
    i18n_probabilidad_ser_infeccioso: 'Probabilidad de ser infeccioso',
    i18n_tasa_hospitalizacion: 'Tasa de hospitalización',
    i18n_indice_mortalidad: 'Índice de mortalidad',
    i18n_resultado_condicional_evento: 'Resultado condicional/evento',
    i18n_una_persona_un_evento: 'UNA PERSONA / UN EVENTO',
    i18n_prob_infeccion: 'Prob. infección',
    i18n_prob_hospitalizacion: 'Prob. hospitalización',
    i18n_prob_muerte: 'Prob. muerte',
    i18n_relacion_riesgo_muerte_automovil: 'Relación con el riesgo de muerte por viaje en automóvil',
    i18n_todos_asistentes_evento: 'TODOS LOS ASISTENTES / UN EVENTO',
    i18n_casos_covid_surgidos: 'Casos COVID surgidos',
    i18n_hospitalizaciones_surgidas: 'Hospitalizaciones surgidas',
    i18n_muertes_surgidas: 'Muertes surgidas',
    i18n_resultado_absoluto_evento: 'Resultado absoluto/evento',
    i18n_co2_inhalar: 'CO2 para inhalar 1 hora para infectar al 1% (ppm)',
    i18n_resultado_absoluto_multiples_veces: 'Resultado absoluto/multiples veces',
    i18n_notas_particulares: 'Notas particulares para este caso',
    i18n_mas_info: 'Más Información'
}