const pt = {
    i18n_titulo: 'Calc. Riscos Aerossóis',
    i18n_descripcion: 'Selecciona o lugar/estância sobre a qual se quer calcular a transmissão de riscos por aerossóis da <b>COVID-19</b>',
    i18n_subdivision: 'Lugar / Estância',
    i18n_class: 'Classe',
    i18n_coro: 'Coro',
    i18n_estadio: 'Estádio',
    i18n_metro: 'Metro',
    i18n_super: 'Supermercado',
    i18n_tasa_ventilacion_persona: 'Taxa de ventilação por pessoa',
    i18n_l_s_persona: 'L/s/pessoa',
    i18n_parametros_ambientales: 'Parâmetros ambientais',
    i18n_largo: 'Comprimento',
    i18n_ancho: 'Largura',
    i18n_alto: 'Altura',
    i18n_duracion_evento: 'Duração evento',
    i18n_n_rep_evento: 'Nº rep. evento',
    i18n_cambios_aire: 'Mudanças de ar',
    i18n_mostrar: 'Mostrar',
    i18n_ocultar: 'Ocultar',
    i18n_parametros_avanzados: 'Parâmetros avançados',
    i18n_presion: 'Pressão',
    i18n_temperatura: 'Temperatura',
    i18n_humedad: 'Humidade',
    i18n_co2_aire_libre: 'CO2 ao ar livre',
    i18n_tasa_descomposicon: 'Taxa descomposição',
    i18n_deposicon_superficies: 'Deposição superficies',
    i18n_medidas_control_adicionales: 'Medidas controlo adicionais',
    i18n_densidad_area_persona: 'Densidade <br /> (área/pessoa)',
    i18n_ft_persona: 'sq ft/pessoa',
    i18n_persona_m2: 'pessoa/m2',
    i18n_m3_persona: 'm3/pessoa',
    i18n_parametros_personas_actividad: 'Parâmetros Pessoas & Actividade',
    i18n_n_personas: 'Nº Pessoas',
    i18n_poblacion_inmune: 'População imune',
    i18n_frec_respiratoria: 'Frec. respiratória',
    i18n_exhalacion_cuantica: 'Exalação quántica',
    i18n_ef_mascarilla_exhalacion: 'Ef. máscara exalação',
    i18n_personas_con_mascarillas: 'Pessoas com máscaras',
    i18n_ef_mascarilla_inhalacion: 'Ef. máscara inalação',
    i18n_personas_infecciosas: 'Pessoas infecciosas',
    i18n_tasa_co2_por_persona: 'Taxa CO2 por pessoa',
    i18n_parametros_covid19: 'Parâmetros COVID-19',
    i18n_probabilidad_ser_infeccioso: 'Probabilidade de ser infeccioso',
    i18n_tasa_hospitalizacion: 'Taxa de hospitalização',
    i18n_indice_mortalidad: 'Índice de mortalidade',
    i18n_resultado_condicional_evento: 'Resultado condicional/evento',
    i18n_una_persona_un_evento: 'UMA PESSOA / UM EVENTO',
    i18n_prob_infeccion: 'Prob. infecção',
    i18n_prob_hospitalizacion: 'Prob. hospitalização',
    i18n_prob_muerte: 'Prob. morte',
    i18n_relacion_riesgo_muerte_automovil: 'Relação com o risco de morte por viagem em automóvel',
    i18n_todos_asistentes_evento: 'TODOS OS ASSISTENTES / UM EVENTO',
    i18n_casos_covid_surgidos: 'Casos COVID novos',
    i18n_hospitalizaciones_surgidas: 'Hospitalizações novas',
    i18n_muertes_surgidas: 'Novas mortes',
    i18n_resultado_absoluto_evento: 'Resultado absoluto/evento',
    i18n_co2_inhalar: 'CO2 para inalar 1 hora para infectar a 1% (ppm)',
    i18n_resultado_absoluto_multiples_veces: 'Resultado absoluto/multiplas vezes',
    i18n_notas_particulares: 'Notas particulares para este caso',
    i18n_mas_info: 'Mais Informação'
}